// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OceanicAirlines.Models
{
    public partial class Bookingline
    {
        public int Id { get; set; }
        public int LineId { get; set; }
        public int SegmentId { get; set; }
        public int StartPosId { get; set; }
        public int EndPosId { get; set; }
        public int TransportId { get; set; }
        public int ParcelId { get; set; }
        public int TypeId { get; set; }
        public decimal? Price { get; set; }
        public decimal? DistanceInHours { get; set; }
        public string Currency { get; set; }

        public virtual City EndPos { get; set; }
        public virtual City StartPos { get; set; }
    }
}