// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OceanicAirlines.Models
{
    public partial class Parcel
    {
        public int Id { get; set; }
        public decimal? WeightInKg { get; set; }
        public decimal? HeightInCm { get; set; }
        public decimal? WidthInCm { get; set; }
        public decimal? LengthInCm { get; set; }
        public decimal? Price { get; set; }
        public string Currency { get; set; }
    }
}