// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OceanicAirlines.Models
{
    public partial class Transporttype
    {
        public int Id { get; set; }
        public string TransportType1 { get; set; }
    }
}