// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OceanicAirlines.Models
{
    public partial class Type
    {
        public int Id { get; set; }
        public string Type1 { get; set; }
        public decimal? Factor { get; set; }
        public bool Active { get; set; }
    }
}