// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using OceanicAirlines.Models;

namespace OceanicAirlines.Services
{
    public partial class DbOaDk1Context : DbContext
    {
        public DbOaDk1Context()
        {
        }

        public DbOaDk1Context(DbContextOptions<DbOaDk1Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Bookingline> Bookingline { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Parcel> Parcel { get; set; }
        public virtual DbSet<Models.Route> Route { get; set; }
        public virtual DbSet<Transporttype> Transporttype { get; set; }
        public virtual DbSet<Models.Type> Type { get; set; }
        public virtual DbSet<User> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Booking>(entity =>
            {
                entity.ToTable("BOOKING", "DATA");

                entity.Property(e => e.CustomerId).HasColumnName("CustomerID");

                entity.Property(e => e.EndPosId).HasColumnName("EndPosID");

                entity.Property(e => e.StartPosId).HasColumnName("StartPosID");

                entity.Property(e => e.UserId).HasColumnName("UserID");
            });

            modelBuilder.Entity<Bookingline>(entity =>
            {
                entity.HasKey(e => new { e.Id, e.LineId, e.SegmentId })
                    .HasName("PK_DATA_BOOKINGLINE");

                entity.ToTable("BOOKINGLINE", "DATA");

                entity.Property(e => e.LineId).HasColumnName("LineID");

                entity.Property(e => e.SegmentId).HasColumnName("SegmentID");

                entity.Property(e => e.Currency)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('USD')");

                entity.Property(e => e.DistanceInHours).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.EndPosId).HasColumnName("EndPosID");

                entity.Property(e => e.ParcelId).HasColumnName("ParcelID");

                entity.Property(e => e.Price).HasColumnType("decimal(17, 2)");

                entity.Property(e => e.StartPosId).HasColumnName("StartPosID");

                entity.Property(e => e.TransportId).HasColumnName("TransportID");

                entity.Property(e => e.TypeId).HasColumnName("TypeID");
            });

            modelBuilder.Entity<City>(entity =>
            {
                entity.ToTable("CITY", "DATA");

                entity.Property(e => e.CityName).HasMaxLength(255);
            });

            modelBuilder.Entity<Customer>(entity =>
            {
                entity.ToTable("CUSTOMER", "DATA");

                entity.Property(e => e.Address).HasMaxLength(255);

                entity.Property(e => e.City).HasMaxLength(255);

                entity.Property(e => e.Country)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.ZipCode)
                    .HasMaxLength(12)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Parcel>(entity =>
            {
                entity.ToTable("PARCEL", "DATA");

                entity.Property(e => e.Currency)
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasDefaultValueSql("('USD')");

                entity.Property(e => e.HeightInCm).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.LengthInCm).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.Price).HasColumnType("decimal(17, 2)");

                entity.Property(e => e.WeightInKg).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.WidthInCm).HasColumnType("decimal(10, 2)");
            });

            modelBuilder.Entity<Models.Route>(entity =>
            {
                entity.ToTable("ROUTE", "DATA");

                entity.Property(e => e.DistanceInHours).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.EndPosId)
                    .HasMaxLength(9)
                    .HasColumnName("EndPosID");

                entity.Property(e => e.StartPosId)
                    .HasMaxLength(9)
                    .HasColumnName("StartPosID");
            });

            modelBuilder.Entity<Transporttype>(entity =>
            {
                entity.ToTable("TRANSPORTTYPE", "DATA");

                entity.Property(e => e.TransportType1)
                    .HasMaxLength(100)
                    .HasColumnName("TransportType");
            });

            modelBuilder.Entity<Models.Type>(entity =>
            {
                entity.ToTable("TYPE", "DATA");

                entity.Property(e => e.Factor).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.Type1)
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnName("Type");
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("USER", "DATA");

                entity.Property(e => e.Mail)
                    .IsRequired()
                    .HasMaxLength(255);

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(64)
                    .IsUnicode(false)
                    .IsFixedLength();

                entity.Property(e => e.Type)
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}